# Generated by Django 6.0.4 on 2026-05-13 17:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id_livre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('auteur', models.CharField(max_length=200, verbose_name='Auteur')),
                ('annee_publication', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1450), django.core.validators.MaxValueValidator(2026)], verbose_name='Année de publication')),
                ('quantite_disponible', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité disponible')),
                ('quantite_totale', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité totale')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunté'), ('reserve', 'Réservé'), ('indisponible', 'Indisponible')], default='disponible', max_length=20, verbose_name='Statut')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to='livres.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_nom', models.CharField(max_length=150, verbose_name="Nom de l'emprunteur")),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_reelle', models.DateField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to=settings.AUTH_USER_MODEL)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='livres.livre')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-date_emprunt'],
            },
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['titre'], name='livres_livr_titre_7cb81f_idx'),
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['auteur'], name='livres_livr_auteur_5647a2_idx'),
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['categorie'], name='livres_livr_categor_db3c2c_idx'),
        ),
    ]
