# Generated by Django 6.0.4 on 2026-05-30 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_chatbot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Chatbot',
                'verbose_name_plural': 'Conversations Chatbot',
                'ordering': ['-date_creation'],
            },
        ),
    ]
