# Generated by Django 6.0.4 on 2026-05-05 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livre',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
        migrations.AlterField(
            model_name='livre',
            name='annee_publication',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1450), django.core.validators.MaxValueValidator(2026)], verbose_name='Année de publication'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to='livres.categorie', verbose_name='Catégorie'),
        ),
    ]
